from Shooter import *
pygame.display.set_caption("Shoot 'em 'up Engine")
load_bg(['0', '1', '0', '0', '2', '3'])
load_images(['1', '2', '0', '3'])
load_object(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
Entity(entitys['0'])
load_level('2')
load_map('2')
Entity(entitys['1'])
initgame()
play(spd=0.5)